### PR TITLE
feat: add stories for `@nuxtjs/storybook`

### PR DESCRIPTION
**Pull request by farnabaz**
`@nuxtjs/storybook` does provide and custom hook for modules to register their own stories. https://github.com/nuxt-community/storybook/pull/129

This PR is a proposal for Icons story for font-awesome module
Screen Shot 2020-10-06 at 4 36 01 PM

### CODE REVIEW

**Comment by pimlie** [comment]
@farnabaz Thank you for this pr and your work on the storybook module.

Could we make the inclusion of these module stories optional? Ie we shouldnt force module stories into existing storybook configs.

**Comment by farnabaz** [comment]
By default module stories will include in storybook but there is an `exclude` option in Storybook config that can be used to ignore modules.

**Comment by pimlie** [comment]
Ah nice. Could we add an entry to the readme about how storybook integrates with fontawesome module? I dont think its the sole responsibility of storybook module to inform people how evertyhing is supposed to work, but it can be just a link to the specific page about module integration in the storybook docs

**Comment by farnabaz** [comment]
It's great idea to add an entry in readme, I will create the entry, But first I have to release `@nustjs/storybook`.

**Review by pimlie — APPROVED** [review]

**Comment by farnabaz** [comment]
I've made some changes.
- Copy icon tag to clipboard on click
- Create size control for icons

**Comment by pimlie** [comment]
@farnabaz Sorry for the delay, is this still good to merge?

**Comment by farnabaz** [comment]
@pimlie This is good for me 🙂

**Comment by pimlie** [comment]
Thanks!

**Pull request merged**
